import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/providers/SessionProvider";
import prisma from "@/lib/prisma"; // Fetches data from DB
import Script from "next/script"; // Optimizes third-party scripts

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Fetch the active site and its global settings
  const site = await prisma.site.findFirst({ where: { isActive: true } });
  const settings = site
    ? await prisma.globalSettings.findUnique({ where: { siteId: site.id } })
    : null;

  const analytics = settings?.analytics || {};
  const scripts = settings?.scripts || {};

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        {/* This injects your custom code into the <head> tag */}
        {scripts.head && (
          <div dangerouslySetInnerHTML={{ __html: scripts.head }} />
        )}
      </head>
      <body>
        {/* This injects your custom code at the start of the <body> tag */}
        {scripts.body && (
          <div dangerouslySetInnerHTML={{ __html: scripts.body }} />
        )}

        {/* Google Tag Manager */}
        {analytics.googleTagManagerId && (
          <Script id="google-tag-manager" strategy="afterInteractive">
            {`
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','${analytics.googleTagManagerId}');
            `}
          </Script>
        )}

        {/* Google Analytics (gtag.js) */}
        {analytics.googleAnalyticsId && (
          <>
            <Script
              strategy="afterInteractive"
              src={`https://www.googletagmanager.com/gtag/js?id=${analytics.googleAnalyticsId}`}
            />
            <Script id="google-analytics" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${analytics.googleAnalyticsId}');
              `}
            </Script>
          </>
        )}

        {/* Microsoft Clarity */}
        {analytics.clarityId && (
          <Script id="microsoft-clarity" strategy="afterInteractive">
            {`
              (function(c,l,a,r,i,t,y){
                  c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                  t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/v/"+i;
                  y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "${analytics.clarityId}");
            `}
          </Script>
        )}

        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
